# This is a complete config file. For live examples, see the testdata/ folder.

# the name of the docker image to pull
image = "sourcegraph/server"

# optional: if you are using a custom registry, change this prefix
registry = "https://registry.hub.docker.com/v1/repositories/"

blacklist = ["insiders", "rc"]

# If you only want certain images, set this whitelist. ie, "alpine", "light", etc
whitelist = "light"

# Removes prefix. Note the trailing dash - the prefix is removed EXACTLY as provided.
strip_prefix = "linux-arm-"

# Removes suffix. Note leading dash - the suffix is removed EXACTLY as provided.
strip_suffix = "-alpine"