# the name of the docker image to pull
image = "sourcegraph/server"

# optional: if you are using a custom registry, change this prefix
registry = "https://registry.hub.docker.com/v1/repositories/"

blacklist = ["insiders", "rc"]

# comments
whitelist = "alpine"

# Remove prefix. Note the trailing dash.
strip_prefix = "linux-arm-"

# Removes suffix. Note leading dash.
strip_suffix = "-alpine"